### ISSUE TITLE
HTTP 500 when trying to enable 2FA

### ISSUE THREAD

**Issue by danielmbrasil** [Codeminer42/Punchclock#420] opened 2023-05-23 18:07 UTC
**Steps to reproduce the issue**
1. Open `/user` page
2. Click on `Enable 2FA`

**Expected behavior**
Page loads correctly

**Actual behavior**
HTTP 500

**Comment by adbatista** [comment] 2023-10-03 18:36
duplicate of https://github.com/Codeminer42/Punchclock/issues/419

**Closed by adbatista** 2023-10-03 18:36 UTC
